AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: historial-ofertas

Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  HistorialOfertasFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'applications-db'
        - SQSSendMessagePolicy:
            QueueName: !ImportValue TelegramMessageQueueName
      Environment:
        Variables:
          SQS_QUEUE_URL: !ImportValue TelegramMessageQueueUrl
          ENVIRONMENT: prod
      Events:
        HistorialOfertasSchedule:
          Type: Schedule
          Properties:
            Schedule: 'rate(2 minutes)'
            Name: HistorialOfertasSchedule
            Description: Historial ofertas schedule
            Enabled: false
